separator = " / "

[audio]
mute = " mute"
template = " vol {VOL}%"

[backlight]
device = "amdgpu_bl1"
template = "bl {BL}%"

[battery]
notifier_levels = [ 2, 5, 10, 15, 20 ]

[time]
format = "%H:%M "
