separator = "] ["

[audio]
mute = " [muted"
template = " [s{VOL}%"

[backlight]
device = "amdgpu_bl1"
template = "b{BL}%"

[battery]
enable_notifier = false

[time]
format = "%H:%M] "

[network]
no_value = "?"
template = "{ESSID} {LocalIPv4}"
